import {
  Laptop,
  Shirt,
  Home,
  Dumbbell,
  BookOpen,
  Gamepad2,
  Smartphone,
  Monitor,
  Camera,
  Headphones,
  Watch,
  Footprints,
  Sparkles,
  HeartPulse,
  Sofa,
  UtensilsCrossed,
  Tent,
  Sprout,
  Baby,
  Bone,
  Music,
  Clapperboard,
  ShoppingBasket,
  Car,
  Wrench,
  Briefcase,
  Palette,
  Gift,
  Gem,
  Cpu,
  type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  // Tecnología y electrónica
  laptop: Laptop,
  electronica: Laptop,
  electronics: Laptop,
  tecnologia: Cpu,
  technology: Cpu,
  tech: Cpu,
  cpu: Cpu,
  smartphone: Smartphone,
  telefonia: Smartphone,
  celulares: Smartphone,
  moviles: Smartphone,
  phones: Smartphone,
  tv: Monitor,
  television: Monitor,
  televisores: Monitor,
  monitor: Monitor,
  camera: Camera,
  camara: Camera,
  cameras: Camera,
  foto: Camera,
  fotografia: Camera,
  photography: Camera,
  audio: Headphones,
  auriculares: Headphones,
  headphones: Headphones,

  // Moda y accesorios
  shirt: Shirt,
  moda: Shirt,
  fashion: Shirt,
  ropa: Shirt,
  clothing: Shirt,
  zapatos: Footprints,
  shoes: Footprints,
  calzado: Footprints,
  accesorios: Watch,
  accessories: Watch,
  relojes: Watch,
  watch: Watch,
  joyeria: Gem,
  jewelry: Gem,
  joyas: Gem,

  // Hogar y muebles
  home: Home,
  hogar: Home,
  house: Home,
  muebles: Sofa,
  furniture: Sofa,
  sofa: Sofa,
  decoracion: Home,
  decoration: Home,
  cocina: UtensilsCrossed,
  kitchen: UtensilsCrossed,
  electrodomesticos: UtensilsCrossed,
  appliances: UtensilsCrossed,

  // Deportes y aire libre
  dumbbell: Dumbbell,
  deportes: Dumbbell,
  sports: Dumbbell,
  fitness: Dumbbell,
  gym: Dumbbell,
  outdoor: Tent,
  camping: Tent,
  airelibre: Tent,
  jardin: Sprout,
  garden: Sprout,

  // Niños, juguetes y bebés
  gamepad2: Gamepad2,
  juguetes: Gamepad2,
  toys: Gamepad2,
  videojuegos: Gamepad2,
  gaming: Gamepad2,
  consolas: Gamepad2,
  baby: Baby,
  bebe: Baby,
  bebes: Baby,
  infantil: Baby,

  // Libros y medios
  bookopen: BookOpen,
  libros: BookOpen,
  books: BookOpen,
  lectura: BookOpen,
  music: Music,
  musica: Music,
  movies: Clapperboard,
  peliculas: Clapperboard,
  cine: Clapperboard,
  series: Clapperboard,

  // Supermercado, belleza y salud
  supermercado: ShoppingBasket,
  grocery: ShoppingBasket,
  alimentos: ShoppingBasket,
  comida: ShoppingBasket,
  belleza: Sparkles,
  beauty: Sparkles,
  maquillaje: Sparkles,
  cosmeticos: Sparkles,
  salud: HeartPulse,
  health: HeartPulse,
  farmacia: HeartPulse,

  // Mascotas
  mascotas: Bone,
  pets: Bone,
  perros: Bone,
  gatos: Bone,

  // Autos, herramientas, oficina
  autos: Car,
  coches: Car,
  automotriz: Car,
  auto: Car,
  herramientas: Wrench,
  tools: Wrench,
  ferreteria: Wrench,
  oficina: Briefcase,
  office: Briefcase,
  papeleria: Briefcase,

  // Hobbies, regalos, lujo
  arte: Palette,
  art: Palette,
  manualidades: Palette,
  crafts: Palette,
  regalos: Gift,
  gifts: Gift,
  regalo: Gift,
  lujo: Gem,
  luxury: Gem,
}

interface CategoryIconProps {
  iconName?: string | null
  className?: string
}

export function CategoryIcon({ iconName, className = "h-6 w-6" }: CategoryIconProps) {
  const key = iconName?.toLowerCase() ?? ""
  const Icon = iconMap[key] || Laptop
  return <Icon className={className} />
}
